version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=${DEBUG}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - KNOWLEDGE_BASE_PATH=${KNOWLEDGE_BASE_PATH}
      - MAX_REQUESTS=${MAX_REQUESTS}
      - REQUEST_WINDOW=${REQUEST_WINDOW}
      - PORT=${PORT}
    volumes:
      - ./app:/app
      - ./external_knowledge:/app/external_knowledge